# This file contains values from Cookiecutter

default_context:
  project_name: "embedbase-client"
  project_description: "Awesome `embedbase-client` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "embedbase-client"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "embedbase-py"
  email: "louis@embedbase.xyz"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
